{% set version = "0.4" %}

package:
  name: glue-geospatial
  version: {{ version }}

source:
  fn: glue-geospatial-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glue-geospatial/glue-geospatial-{{ version }}.tar.gz
  sha256: 5261e805e15095bab1339d56412edfad0d5166e1bb7e56ee4b8ff6acf10fc7d6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:

  host:
    - python
    - pip

  run:
    - python
    - numpy
    - astropy
    - pyproj
    - rasterio
    - affine
    - glue-core >=0.13

test:
  imports:
    - rasterio
    - glue_geospatial
    - glue_geospatial.data_factory
    - glue_geospatial.coordinates

about:
  home: https://github.com/glue-viz/glue-geospatial
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Geospatial plugin for glue

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
