{% set version = "0.3" %}

package:
  name: glue-geospatial
  version: {{version}}

source:
  fn: glue-geospatial-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-geospatial/glue-geospatial-{{version}}.tar.gz
  sha256: 760786cea5e76842120a648a4059704eefa9d89da8ddbba0a01aaba0fa91990f

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:

  build:
    - python
    - pip

  run:
    - python
    - numpy
    - astropy
    - pyproj
    - rasterio
    - affine
    - glue-core >=0.13

test:
  imports:
    - rasterio
    - glue_geospatial
    - glue_geospatial.data_factory
    - glue_geospatial.coordinates

about:
  home: https://github.com/glue-viz/glue-geospatial
  license: BSD 3-Clause
  summary: Geospatial plugin for glue

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
